export const APP_TYPES = [
  {
    id: "dashboard",
    label: "Dashboard",
    icon: "chart",
    desc: "A data-rich command center where users monitor KPIs, spot trends in real-time charts, and drill into the metrics that matter. Think Bloomberg Terminal meets modern SaaS.",
  },
  {
    id: "marketing",
    label: "Marketing / Landing",
    icon: "send",
    desc: "A conversion-focused landing page that tells your product's story — bold hero, social proof, feature highlights, and a CTA that demands attention. Every scroll should feel intentional.",
  },
  {
    id: "social",
    label: "Social App",
    icon: "sparkles",
    desc: "A community-first experience built around content feeds, user profiles, and real-time interactions. Think Twitter's information density with Instagram's visual polish.",
  },
  {
    id: "ecommerce",
    label: "E-commerce",
    icon: "briefcase",
    desc: "A storefront that makes browsing feel like discovery. Beautiful product cards, smart filters, a cart that builds urgency, and a checkout flow that removes every ounce of friction.",
  },
  {
    id: "portfolio",
    label: "Portfolio",
    icon: "layers",
    desc: "A personal showcase where your work speaks for itself. Immersive project case studies, a bio that builds trust, and a contact flow that makes hiring you feel effortless.",
  },
  {
    id: "saas",
    label: "SaaS Platform",
    icon: "grid",
    desc: "A product that users live in daily. Clear pricing that sells itself, a feature tour that educates, and an app shell with a sidebar, workspace, and settings that feel instantly familiar.",
  },
  {
    id: "blog",
    label: "Blog / Content",
    icon: "note",
    desc: "A reading experience that keeps people coming back. Clean article layouts with beautiful typography, smart categorization, and a flow that turns casual visitors into loyal readers.",
  },
];

export const CATEGORIES = [
  {
    id: "appType",
    label: "Pick Your Project",
    navLabel: "Project",
    sub: "What kind of app?",
    icon: "grid",
    color: "#5eead4",
    desc: "Choose your project type",
    guidance: "Pick the type of project you're building. This shapes the live preview and gives the AI context for every other setting — or skip it entirely.",
  },
  {
    id: "theme",
    label: "Colors",
    navLabel: "Colors",
    sub: "Palette & mode",
    icon: "palette",
    color: "#818cf8",
    desc: "Color palette & mode",
    guidance: "Start here if you want — or skip it. Pick light or dark mode and a color palette. Everything else adapts to your choice, but nothing is required.",
  },
  {
    id: "mood",
    label: "Mood & Feel",
    navLabel: "Mood",
    sub: "Density & feel",
    icon: "sparkles",
    color: "#a78bfa",
    desc: "Overall feel & vibe",
    guidance: "Define the personality — or don't. Only set the dimensions you care about. The mood shapes spacing, typography weight, and interaction style.",
  },
  {
    id: "cards",
    label: "Card Style",
    navLabel: "Cards",
    sub: "Surface & depth",
    icon: "layers",
    color: "#818cf8",
    desc: "How card surfaces look and feel",
    guidance: "Pick a card style if you want to — totally optional. Fine-tune corners, shadows, borders, and interactions, or just pick a style and roll with the defaults.",
  },
  {
    id: "data",
    label: "Data Display",
    navLabel: "Data",
    sub: "Tables & charts",
    icon: "chart",
    color: "#22c55e",
    desc: "How data is presented",
    guidance: "Skip this if your app isn't data-heavy. Otherwise, pick a display style and fine-tune row density, headers, dividers, and chart treatment.",
  },
  {
    id: "navigation",
    label: "Navigation",
    navLabel: "Navigation",
    sub: "Patterns & controls",
    icon: "compass",
    color: "#67e8f9",
    desc: "How users move through your app",
    guidance: "Pick a navigation pattern if you want specific guidance — or skip it and let the AI figure it out. Each pattern generates concrete CSS for AI coding tools.",
  },
  {
    id: "buttons",
    label: "Buttons",
    navLabel: "Buttons",
    sub: "Actions & CTAs",
    icon: "square",
    color: "#f9a8d4",
    desc: "How buttons and CTAs look and behave",
    guidance: "Buttons are optional too. Pick a style if you want control over CTAs, or leave it blank and the AI will handle it.",
  },
  {
    id: "animation",
    label: "Animation",
    navLabel: "Animation",
    sub: "Motion",
    icon: "zap",
    color: "#fbbf24",
    desc: "Motion & transitions",
    guidance: "Not required — but if you have a preference, set it here. From completely static to rich parallax effects, find your energy level.",
  },
  {
    id: "templates",
    label: "Templates",
    navLabel: "Templates",
    sub: "Pre-built configs",
    icon: "grid",
    color: "#f59e0b",
    desc: "Browse and apply pre-built configurations",
    guidance:
      "Totally optional shortcut. Templates pre-fill sections for you — but you can change anything after, remove sections you don't need, or skip templates entirely and build from scratch.",
  },
  {
    id: "prompt",
    label: "Full Prompt",
    navLabel: "Prompt",
    sub: "View & copy",
    icon: "terminal",
    color: "#a78bfa",
    desc: "Your generated prompt",
    guidance: "Your generated prompt based on whatever you've configured. Even one section is enough — you don't need to fill everything out.",
  },
];
