export const APP_TYPES = [
  {
    id: "dashboard",
    label: "Dashboard",
    icon: "chart",
    desc: "A data-rich command center where users monitor KPIs, spot trends in real-time charts, and drill into the metrics that matter. Think Bloomberg Terminal meets modern SaaS.",
  },
  {
    id: "marketing",
    label: "Marketing / Landing",
    icon: "send",
    desc: "A conversion-focused landing page that tells your product's story — bold hero, social proof, feature highlights, and a CTA that demands attention. Every scroll should feel intentional.",
  },
  {
    id: "social",
    label: "Social App",
    icon: "sparkles",
    desc: "A community-first experience built around content feeds, user profiles, and real-time interactions. Think Twitter's information density with Instagram's visual polish.",
  },
  {
    id: "ecommerce",
    label: "E-commerce",
    icon: "briefcase",
    desc: "A storefront that makes browsing feel like discovery. Beautiful product cards, smart filters, a cart that builds urgency, and a checkout flow that removes every ounce of friction.",
  },
  {
    id: "portfolio",
    label: "Portfolio",
    icon: "layers",
    desc: "A personal showcase where your work speaks for itself. Immersive project case studies, a bio that builds trust, and a contact flow that makes hiring you feel effortless.",
  },
  {
    id: "saas",
    label: "SaaS Platform",
    icon: "grid",
    desc: "A product that users live in daily. Clear pricing that sells itself, a feature tour that educates, and an app shell with a sidebar, workspace, and settings that feel instantly familiar.",
  },
  {
    id: "blog",
    label: "Blog / Content",
    icon: "note",
    desc: "A reading experience that keeps people coming back. Clean article layouts with beautiful typography, smart categorization, and a flow that turns casual visitors into loyal readers.",
  },
];

export const CATEGORIES = [
  {
    id: "appType",
    label: "What are you building?",
    navLabel: "App Type",
    sub: "App category",
    icon: "briefcase",
    color: "#f472b6",
    desc: "Choose your app type",
    guidance: "Pick the type of app you're building. This shapes the live preview and gives the AI context for every other setting.",
  },
  {
    id: "theme",
    label: "Theme",
    navLabel: "Theme",
    sub: "Colors & palette",
    icon: "palette",
    color: "#818cf8",
    desc: "Color palette & style",
    guidance: "Set the visual foundation. Your theme controls background, card, accent, and text colors throughout the entire UI.",
  },
  {
    id: "mood",
    label: "Mood & Feel",
    navLabel: "Mood",
    sub: "Density & feel",
    icon: "sparkles",
    color: "#a78bfa",
    desc: "Overall feel & vibe",
    guidance: "Define the personality. Is this corporate and polished, or playful and fun? The mood shapes spacing, typography weight, and interaction style.",
  },
  {
    id: "cards",
    label: "Card Style",
    navLabel: "Cards",
    sub: "Surface & depth",
    icon: "layers",
    color: "#818cf8",
    desc: "How card surfaces look and feel",
    guidance: "Pick a card style that matches your app's personality, then fine-tune corners, shadows, borders, and interactions.",
  },
  {
    id: "data",
    label: "Data Display",
    navLabel: "Data",
    sub: "Tables & charts",
    icon: "chart",
    color: "#22c55e",
    desc: "How data is presented",
    guidance: "Define how tables and charts should look.",
  },
  {
    id: "navigation",
    label: "Navigation",
    navLabel: "Navigation",
    sub: "Patterns & controls",
    icon: "compass",
    color: "#67e8f9",
    desc: "How users move through your app",
    guidance: "Pick a navigation pattern, then fine-tune the details. Each pattern generates concrete CSS guidance for AI coding tools.",
  },
  {
    id: "buttons",
    label: "Buttons",
    navLabel: "Buttons",
    sub: "Actions & CTAs",
    icon: "square",
    color: "#f9a8d4",
    desc: "How buttons and CTAs look and behave",
    guidance: "Pick a button style, then fine-tune size, corners, shadows, and interactions across primary, secondary, and tertiary tiers.",
  },
  {
    id: "animation",
    label: "Animation",
    navLabel: "Animation",
    sub: "Motion",
    icon: "zap",
    color: "#fbbf24",
    desc: "Motion & transitions",
    guidance: "Control how much motion your UI has. From completely static to rich parallax effects — find the right energy level.",
  },
  {
    id: "appDescription",
    label: "App Description",
    navLabel: "App Info",
    sub: "Name & desc",
    icon: "edit",
    color: "#5eead4",
    desc: "What you're building",
    guidance: "Tell the AI what your app does. The more context you provide, the more tailored the generated UI prompt will be.",
  },
  {
    id: "awsGuidelines",
    label: "AWS Guidelines",
    navLabel: "AWS",
    sub: "Brand",
    icon: "aws",
    color: "#fdba74",
    desc: "Brand compliance",
    guidance: "Toggle on to inject AWS branding rules — orange accents, Ember font, 8px spacing grid, and component patterns.",
  },
  {
    id: "customNotes",
    label: "Custom Notes",
    navLabel: "Notes",
    sub: "Extra",
    icon: "note",
    color: "#94a3b8",
    desc: "Extra instructions",
    guidance: "Add any specific instructions the AI should follow. Library preferences, accessibility needs, special behaviors — anything goes.",
  },
  {
    id: "prompt",
    label: "Full Prompt",
    navLabel: "Prompt",
    sub: "View & copy",
    icon: "terminal",
    color: "#a78bfa",
    desc: "Your generated prompt",
    guidance: "This is your complete generated prompt based on all configured sections. Copy it and paste into your AI coding tool.",
  },
];
