// ── Mood Presets v4 ──
// 8 dramatically different archetypes, each with a visual config for the mini-preview

export const MOOD_PRESETS = [
  {
    id: "boardroom",
    name: "Boardroom",
    tagline: "Polished. Poised. Pitch-ready.",
    icon: "briefcase",
    density: "balanced",
    typography: "clean",
    interaction: "smooth",
    embellishment: "minimal",
    promptText:
      "Professional, restrained design. Clean sans-serif, balanced whitespace, muted palette with one accent color. No gradients or glow. Enterprise-ready.",
    v: {
      bg: "#0f1219", card: "#181c27", accent: "#6366f1", text: "#e2e0db",
      muted: "rgba(226,224,219,0.3)", dimmer: "rgba(226,224,219,0.15)",
      radius: 10, font: "'DM Sans', sans-serif", headSize: 11, headWeight: 600,
      valSize: 18, valWeight: 700, valFont: "'DM Sans', sans-serif",
      labelSize: 6, labelCase: "uppercase", labelSpacing: "0.08em",
      cardPad: 10, gap: 8, cardCount: 3, barCount: 14, barGap: 3,
      showNav: false, showTabs: true, tabStyle: "pill",
      border: "1px solid rgba(255,255,255,0.06)", shadow: "none",
      glass: false, glow: false, brutalist: false, light: false,
      headText: "Overview", chartLabel: "Performance",
      barAccentStart: 11, titleDecor: "", statSet: "default",
    },
  },
  {
    id: "hackmode",
    name: "Hack Mode",
    tagline: "Dense. Mono. Zero fluff.",
    icon: "terminal",
    density: "dense",
    typography: "technical",
    interaction: "snappy",
    embellishment: "none",
    promptText:
      "Dense, monospace-driven interface. JetBrains Mono everywhere, tight 4-6px spacing, no border-radius, uppercase labels with wide letter-spacing. Terminal aesthetic.",
    v: {
      bg: "#0a0a0a", card: "#111111", accent: "#22c55e", text: "#a3a3a3",
      muted: "rgba(163,163,163,0.4)", dimmer: "rgba(163,163,163,0.15)",
      radius: 0, font: "'JetBrains Mono', monospace", headSize: 9, headWeight: 500,
      valSize: 14, valWeight: 500, valFont: "'JetBrains Mono', monospace",
      labelSize: 5, labelCase: "uppercase", labelSpacing: "0.12em",
      cardPad: 6, gap: 4, cardCount: 4, barCount: 24, barGap: 1,
      showNav: true, showTabs: false, tabStyle: "none",
      border: "1px solid #1a1a1a", shadow: "none",
      glass: false, glow: false, brutalist: false, light: false,
      headText: "> sys_monitor", chartLabel: "> THROUGHPUT [5m]",
      barAccentStart: 20, titleDecor: "", statSet: "terminal",
    },
  },
  {
    id: "frontpage",
    name: "Front Page",
    tagline: "Serif headlines. Generous whitespace.",
    icon: "type",
    density: "spacious",
    typography: "editorial",
    interaction: "smooth",
    embellishment: "moderate",
    promptText:
      "Editorial, magazine-quality design. Georgia or serif headlines (italic), generous padding 20px+, 2-column layouts where appropriate, elegant dividers. Content-first, typography-driven.",
    v: {
      bg: "#faf8f4", card: "#ffffff", accent: "#1a1a2e", text: "#1a1a2e",
      muted: "rgba(26,26,46,0.45)", dimmer: "rgba(26,26,46,0.12)",
      radius: 4, font: "Georgia, serif", headSize: 15, headWeight: 400,
      valSize: 20, valWeight: 400, valFont: "Georgia, serif",
      labelSize: 7, labelCase: "normal", labelSpacing: "0.02em",
      cardPad: 14, gap: 12, cardCount: 3, barCount: 10, barGap: 4,
      showNav: false, showTabs: true, tabStyle: "underline",
      border: "1px solid rgba(0,0,0,0.08)", shadow: "0 1px 3px rgba(0,0,0,0.04)",
      glass: false, glow: false, brutalist: false, light: true,
      headText: "The Weekly", chartLabel: "Readership",
      barAccentStart: 7, titleDecor: "italic", statSet: "editorial",
    },
  },
  {
    id: "arcade",
    name: "Arcade",
    tagline: "Bouncy. Bold. Full personality.",
    icon: "zap",
    density: "balanced",
    typography: "rounded",
    interaction: "dramatic",
    embellishment: "rich",
    promptText:
      "Playful, energetic design. Rounded font (Nunito 800), 16-20px border-radius, bouncy hover animations with scale(1.06), vibrant gradients, glassmorphism cards, progress indicators.",
    v: {
      bg: "#120b20", card: "rgba(255,255,255,0.05)", accent: "#e879f9", text: "#f5f0ff",
      muted: "rgba(245,240,255,0.4)", dimmer: "rgba(245,240,255,0.15)",
      radius: 18, font: "'Nunito', sans-serif", headSize: 12, headWeight: 800,
      valSize: 18, valWeight: 800, valFont: "'Nunito', sans-serif",
      labelSize: 7, labelCase: "normal", labelSpacing: "0",
      cardPad: 10, gap: 8, cardCount: 3, barCount: 12, barGap: 3,
      showNav: false, showTabs: true, tabStyle: "pill",
      border: "1px solid rgba(255,255,255,0.08)", shadow: "0 0 20px rgba(232,121,249,0.1)",
      glass: true, glow: true, brutalist: false, light: false,
      headText: "Player Hub", chartLabel: "Activity",
      barAccentStart: 9, titleDecor: "", statSet: "playful",
    },
  },
  {
    id: "warroom",
    name: "War Room",
    tagline: "Max density. Real-time everything.",
    icon: "radar",
    density: "dense",
    typography: "technical",
    interaction: "snappy",
    embellishment: "minimal",
    promptText:
      "Operations/monitoring density. JetBrains Mono, 3-5px spacing, status indicators, amber/red alert colors, multi-panel grid layout. Designed for information overload.",
    v: {
      bg: "#050a12", card: "#0a1020", accent: "#f59e0b", text: "#94a3b8",
      muted: "rgba(148,163,184,0.4)", dimmer: "rgba(148,163,184,0.15)",
      radius: 2, font: "'JetBrains Mono', monospace", headSize: 8, headWeight: 600,
      valSize: 13, valWeight: 600, valFont: "'JetBrains Mono', monospace",
      labelSize: 5, labelCase: "uppercase", labelSpacing: "0.1em",
      cardPad: 5, gap: 3, cardCount: 4, barCount: 28, barGap: 1,
      showNav: true, showTabs: false, tabStyle: "none",
      border: "1px solid #1a2540", shadow: "none",
      glass: false, glow: false, brutalist: false, light: false,
      headText: "OPS_CTR", chartLabel: "SYS LOAD [5m]",
      barAccentStart: 24, titleDecor: "", statSet: "ops",
    },
  },
  {
    id: "rawcut",
    name: "Raw Cut",
    tagline: "No radius. No shadows. No apologies.",
    icon: "slash",
    density: "balanced",
    typography: "clean",
    interaction: "subtle",
    embellishment: "none",
    promptText:
      "Brutalist design. Zero border-radius, zero box-shadow, hard 2px borders, stark contrast. Heavy uppercase typography, aggressive spacing. Anti-decoration as the aesthetic.",
    v: {
      bg: "#f0f0f0", card: "#ffffff", accent: "#000000", text: "#000000",
      muted: "rgba(0,0,0,0.4)", dimmer: "rgba(0,0,0,0.1)",
      radius: 0, font: "'DM Sans', sans-serif", headSize: 13, headWeight: 900,
      valSize: 18, valWeight: 900, valFont: "'DM Sans', sans-serif",
      labelSize: 6, labelCase: "uppercase", labelSpacing: "0.1em",
      cardPad: 8, gap: 5, cardCount: 3, barCount: 12, barGap: 2,
      showNav: false, showTabs: true, tabStyle: "underline-bold",
      border: "2px solid #000", shadow: "none",
      glass: false, glow: false, brutalist: true, light: true,
      headText: "METRICS", chartLabel: "OUTPUT",
      barAccentStart: 9, titleDecor: "", statSet: "brutalist",
    },
  },
  {
    id: "vapor",
    name: "Vapor",
    tagline: "Frosted layers. Soft glow. Dreamy.",
    icon: "layers",
    density: "spacious",
    typography: "clean",
    interaction: "smooth",
    embellishment: "rich",
    promptText:
      "Glassmorphism design. Frosted translucent cards with backdrop-filter blur(20px), layered depth with subtle gradients, soft accent glow (box-shadow with color), rounded 14-18px radius.",
    v: {
      bg: "#0c0f1a", card: "rgba(255,255,255,0.04)", accent: "#67e8f9", text: "#e0f2fe",
      muted: "rgba(224,242,254,0.35)", dimmer: "rgba(224,242,254,0.12)",
      radius: 16, font: "'DM Sans', sans-serif", headSize: 12, headWeight: 600,
      valSize: 18, valWeight: 700, valFont: "'DM Sans', sans-serif",
      labelSize: 7, labelCase: "normal", labelSpacing: "0.02em",
      cardPad: 12, gap: 10, cardCount: 2, barCount: 12, barGap: 3,
      showNav: false, showTabs: true, tabStyle: "pill",
      border: "1px solid rgba(255,255,255,0.08)", shadow: "0 8px 32px rgba(0,0,0,0.2)",
      glass: true, glow: true, brutalist: false, light: false,
      headText: "Signals", chartLabel: "Frequency",
      barAccentStart: 9, titleDecor: "", statSet: "glass",
    },
  },
  {
    id: "midnight",
    name: "Midnight Luxe",
    tagline: "Dark. Rich. Gold-trimmed.",
    icon: "crown",
    density: "balanced",
    typography: "clean",
    interaction: "smooth",
    embellishment: "moderate",
    promptText:
      "Premium dark design. Near-black backgrounds (#08090d), warm gold accent (#d4a254), subtle gold-tinted borders, refined spacing. Luxury fintech or private portal feel.",
    v: {
      bg: "#08090d", card: "#12141c", accent: "#d4a254", text: "#e8e4dc",
      muted: "rgba(232,228,220,0.35)", dimmer: "rgba(232,228,220,0.12)",
      radius: 12, font: "'DM Sans', sans-serif", headSize: 11, headWeight: 700,
      valSize: 18, valWeight: 700, valFont: "'DM Sans', sans-serif",
      labelSize: 6, labelCase: "uppercase", labelSpacing: "0.08em",
      cardPad: 10, gap: 8, cardCount: 3, barCount: 14, barGap: 3,
      showNav: false, showTabs: true, tabStyle: "pill",
      border: "1px solid rgba(212,162,84,0.12)", shadow: "0 2px 12px rgba(0,0,0,0.3)",
      glass: false, glow: false, brutalist: false, light: false,
      headText: "Portfolio", chartLabel: "Returns",
      barAccentStart: 11, titleDecor: "", statSet: "luxe",
    },
  },
];

// ── Fine-tune dimensions ──
export const MOOD_DIMS = {
  density: {
    label: "Density",
    desc: "How packed is the UI",
    color: "#3b82f6",
    opts: [
      { id: "spacious", label: "Spacious", desc: "Generous whitespace, large touch targets" },
      { id: "balanced", label: "Balanced", desc: "Standard padding, comfortable reading" },
      { id: "compact", label: "Compact", desc: "Tighter spacing, more content visible" },
      { id: "dense", label: "Dense", desc: "Maximum info density, minimal padding" },
    ],
  },
  typography: {
    label: "Typography",
    desc: "Font personality",
    color: "#a855f7",
    opts: [
      { id: "clean", label: "Clean", desc: "Modern sans-serif, neutral and professional" },
      { id: "technical", label: "Technical", desc: "Monospace-heavy, code-like precision" },
      { id: "editorial", label: "Editorial", desc: "Serif accents, magazine-quality hierarchy" },
      { id: "rounded", label: "Rounded", desc: "Soft, friendly fonts with personality" },
    ],
  },
  interaction: {
    label: "Interaction",
    desc: "Hover and transition energy",
    color: "#f59e0b",
    opts: [
      { id: "subtle", label: "Subtle", desc: "Gentle opacity shifts, understated" },
      { id: "smooth", label: "Smooth", desc: "Fluid easing, polished transitions" },
      { id: "snappy", label: "Snappy", desc: "Quick, responsive, satisfying clicks" },
      { id: "dramatic", label: "Dramatic", desc: "Bold transforms, scale shifts, glows" },
    ],
  },
  embellishment: {
    label: "Embellishment",
    desc: "Visual extras",
    color: "#10b981",
    opts: [
      { id: "none", label: "None", desc: "Pure content, zero decoration" },
      { id: "minimal", label: "Minimal", desc: "Subtle borders and light shadows" },
      { id: "moderate", label: "Moderate", desc: "Gradients, shadows, accent borders" },
      { id: "rich", label: "Rich", desc: "Glows, glass effects, layered textures" },
    ],
  },
};

// ── Quick combos (mood + project type pairings) ──
export const MOOD_COMBOS = [
  { mood: "boardroom", purpose: "keynote", label: "Corporate Deck", desc: "Polished presentation for leadership" },
  { mood: "arcade", purpose: "hangout", label: "Team Rally", desc: "Fun internal engagement tool" },
  { mood: "warroom", purpose: "command-center", label: "Ops Dashboard", desc: "Real-time monitoring center" },
  { mood: "vapor", purpose: "showroom", label: "Product Launch", desc: "Dreamy product showcase" },
  { mood: "frontpage", purpose: "handbook", label: "Knowledge Base", desc: "Editorial documentation site" },
  { mood: "midnight", purpose: "number-cruncher", label: "Executive Intel", desc: "Premium analytics portal" },
];

export const DEFAULT_MOOD_DIMENSIONS = {
  density: "balanced",
  typography: "clean",
  interaction: "smooth",
  embellishment: "minimal",
};

// Prompt descriptions for each dimension value
export const MOOD_PROMPT_MAP = {
  density: {
    spacious: "generous whitespace, large touch targets, breathing room between sections",
    balanced: "standard comfortable spacing, balanced padding",
    compact: "tight spacing, more content visible, reduced padding",
    dense: "maximum information density, minimal padding, every pixel earns its place",
  },
  typography: {
    clean: "modern sans-serif typography (DM Sans, Inter), neutral and professional",
    technical: "monospace-heavy typography (JetBrains Mono, Fira Code), code-like precision and data readability",
    editorial: "serif accents for headings (Georgia, Playfair Display), magazine-quality typographic hierarchy",
    rounded: "soft, friendly fonts (Nunito, Quicksand), rounded letterforms with personality",
  },
  interaction: {
    subtle: "understated hover effects — gentle opacity shifts, minimal motion",
    smooth: "polished transitions — fluid easing (cubic-bezier(0.4, 0, 0.2, 1)), 300-350ms durations",
    snappy: "quick, responsive interactions — 100-150ms ease-out, satisfying click feedback",
    dramatic: "bold hover transforms — scale shifts, glow effects, spring-physics easing",
  },
  embellishment: {
    none: "pure content, zero decoration — flat surfaces and clean geometry only",
    minimal: "subtle borders and light box-shadows only",
    moderate: "gradients, layered shadows, accent-colored borders, subtle depth",
    rich: "glassmorphism, glows, layered textures, backdrop-blur, radial gradients",
  },
};
