// ── Mood Presets v5 ──
// 12 dramatically different archetypes, each with a visual config for the mini-preview

export const MOOD_PRESETS = [
  {
    id: "boardroom",
    name: "Boardroom",
    tagline: "Polished. Poised. Pitch-ready.",
    icon: "briefcase",
    density: "balanced",
    typography: "clean",
    interaction: "smooth",
    embellishment: "minimal",
    promptText:
      'mood-feel: "boardroom" — clean nav with bold logo left and muted links right, thin horizontal rule divider, three equal stat cards large bold values and muted uppercase labels, footer with filled solid button and muted metadata. Typography: geometric sans weight 800 for values and headings. Density: generous 20–24px padding, breathing room between every element. Interaction: smooth 200ms ease, subtle hover lift on cards. Embellishment: single-pixel borders only, no shadows, no radius on buttons — structure carries the weight.',
    v: {
      bg: "#0f1219", card: "#181c27", accent: "#6366f1", text: "#e2e0db",
      muted: "rgba(226,224,219,0.3)", dimmer: "rgba(226,224,219,0.15)",
      radius: 10, font: "'DM Sans', sans-serif", headSize: 11, headWeight: 600,
      valSize: 18, valWeight: 700, valFont: "'DM Sans', sans-serif",
      labelSize: 6, labelCase: "uppercase", labelSpacing: "0.08em",
      cardPad: 10, gap: 8, cardCount: 3, barCount: 14, barGap: 3,
      showNav: false, showTabs: true, tabStyle: "pill",
      border: "1px solid rgba(255,255,255,0.06)", shadow: "none",
      glass: false, glow: false, brutalist: false, light: false,
      headText: "Overview", chartLabel: "Performance",
      barAccentStart: 11, titleDecor: "", statSet: "default",
    },
  },
  {
    id: "hackmode",
    name: "Hack Mode",
    tagline: "Dense. Mono. Zero fluff.",
    icon: "terminal",
    density: "dense",
    typography: "technical",
    interaction: "snappy",
    embellishment: "none",
    promptText:
      'mood-feel: "hack-mode" — monospace top bar with live indicator, tight data cells no border-radius, micro uppercase labels wide letter-spacing, large monospace values, small deltas, mini bar chart in bordered container, tag pills at bottom active one in accent color. Typography: JetBrains Mono everywhere, uppercase labels, code-like precision. Density: maximum — 4–6px gaps, 8–10px padding, every pixel earns its place. Interaction: instant 100ms snappy response, no scale, no glow. Embellishment: zero decoration, flat surfaces, 1px borders only.',
    v: {
      bg: "#0a0a0a", card: "#111111", accent: "#22c55e", text: "#a3a3a3",
      muted: "rgba(163,163,163,0.4)", dimmer: "rgba(163,163,163,0.15)",
      radius: 0, font: "'JetBrains Mono', monospace", headSize: 9, headWeight: 500,
      valSize: 14, valWeight: 500, valFont: "'JetBrains Mono', monospace",
      labelSize: 5, labelCase: "uppercase", labelSpacing: "0.12em",
      cardPad: 6, gap: 4, cardCount: 4, barCount: 24, barGap: 1,
      showNav: true, showTabs: false, tabStyle: "none",
      border: "1px solid #1a1a1a", shadow: "none",
      glass: false, glow: false, brutalist: false, light: false,
      headText: "> sys_monitor", chartLabel: "> THROUGHPUT [5m]",
      barAccentStart: 20, titleDecor: "", statSet: "terminal",
    },
  },
  {
    id: "frontpage",
    name: "Front Page",
    tagline: "Serif headlines. Generous whitespace.",
    icon: "type",
    density: "spacious",
    typography: "editorial",
    interaction: "smooth",
    embellishment: "moderate",
    promptText:
      'mood-feel: "front-page" — serif brand name left and muted date right with 2px bottom rule, two-column grid left 60% right 40%, left column uppercase muted tag + bold serif headline + small body copy, right column thin left border with faded large numbers and bold titles stacked. Typography: editorial serif for headlines and brand, italic for subheadings, light weight for body. Density: spacious 18–22px padding, loose line-height 1.6–1.7. Interaction: smooth 250ms ease, gentle underline on hover links. Embellishment: hairline rules only, no shadows, no radius.',
    v: {
      bg: "#faf8f4", card: "#ffffff", accent: "#1a1a2e", text: "#1a1a2e",
      muted: "rgba(26,26,46,0.45)", dimmer: "rgba(26,26,46,0.12)",
      radius: 4, font: "Georgia, serif", headSize: 15, headWeight: 400,
      valSize: 20, valWeight: 400, valFont: "Georgia, serif",
      labelSize: 7, labelCase: "normal", labelSpacing: "0.02em",
      cardPad: 14, gap: 12, cardCount: 3, barCount: 10, barGap: 4,
      showNav: false, showTabs: true, tabStyle: "underline",
      border: "1px solid rgba(0,0,0,0.08)", shadow: "0 1px 3px rgba(0,0,0,0.04)",
      glass: false, glow: false, brutalist: false, light: true,
      headText: "The Weekly", chartLabel: "Readership",
      barAccentStart: 7, titleDecor: "italic", statSet: "editorial",
    },
  },
  {
    id: "arcade",
    name: "Arcade",
    tagline: "Bouncy. Bold. Full personality.",
    icon: "zap",
    density: "balanced",
    typography: "rounded",
    interaction: "dramatic",
    embellishment: "rich",
    promptText:
      'mood-feel: "arcade" — radial accent glow upper corner, bold rounded logo, accent pill badge, two equal cards border-radius 14px with large bold values, uppercase labels, positive delta below each, full-width accent pill button bottom. Typography: rounded heavy sans weight 900 for values, 700 for labels, all caps for metadata. Density: comfortable 16px padding, generous card spacing. Interaction: bouncy 150ms ease-out, scale(1.04) on hover, satisfying press feel. Embellishment: gradient fills, soft card glow, rounded everything 12–18px throughout.',
    v: {
      bg: "#120b20", card: "rgba(255,255,255,0.05)", accent: "#e879f9", text: "#f5f0ff",
      muted: "rgba(245,240,255,0.4)", dimmer: "rgba(245,240,255,0.15)",
      radius: 18, font: "'Nunito', sans-serif", headSize: 12, headWeight: 800,
      valSize: 18, valWeight: 800, valFont: "'Nunito', sans-serif",
      labelSize: 7, labelCase: "normal", labelSpacing: "0",
      cardPad: 10, gap: 8, cardCount: 3, barCount: 12, barGap: 3,
      showNav: false, showTabs: true, tabStyle: "pill",
      border: "1px solid rgba(255,255,255,0.08)", shadow: "0 0 20px rgba(232,121,249,0.1)",
      glass: true, glow: true, brutalist: false, light: false,
      headText: "Player Hub", chartLabel: "Activity",
      barAccentStart: 9, titleDecor: "", statSet: "playful",
    },
  },
  {
    id: "warroom",
    name: "War Room",
    tagline: "Max density. Real-time everything.",
    icon: "radar",
    density: "dense",
    typography: "technical",
    interaction: "snappy",
    embellishment: "minimal",
    promptText:
      'mood-feel: "war-room" — compact monospace top bar with blinking alert indicator, 4-cell data grid with micro uppercase labels and large monospace values in contextual status tones, mini bar chart with color-coded bars, status tags bottom. Typography: monospace only, 5–7px labels, 13–16px values, no decorative type anywhere. Density: extreme — 3–5px gaps, 5–8px padding, nothing wasted. Interaction: instant 80ms response, no animations, functional only. Embellishment: none — flat dark surfaces, 1px borders, status tones carry all meaning.',
    v: {
      bg: "#050a12", card: "#0a1020", accent: "#f59e0b", text: "#94a3b8",
      muted: "rgba(148,163,184,0.4)", dimmer: "rgba(148,163,184,0.15)",
      radius: 2, font: "'JetBrains Mono', monospace", headSize: 8, headWeight: 600,
      valSize: 13, valWeight: 600, valFont: "'JetBrains Mono', monospace",
      labelSize: 5, labelCase: "uppercase", labelSpacing: "0.1em",
      cardPad: 5, gap: 3, cardCount: 4, barCount: 28, barGap: 1,
      showNav: true, showTabs: false, tabStyle: "none",
      border: "1px solid #1a2540", shadow: "none",
      glass: false, glow: false, brutalist: false, light: false,
      headText: "OPS_CTR", chartLabel: "SYS LOAD [5m]",
      barAccentStart: 24, titleDecor: "", statSet: "ops",
    },
  },
  {
    id: "rawcut",
    name: "Raw Cut",
    tagline: "No radius. No shadows. No apologies.",
    icon: "slash",
    density: "balanced",
    typography: "clean",
    interaction: "subtle",
    embellishment: "none",
    promptText:
      'mood-feel: "raw-cut" — bold uppercase heading top-left, monospace metadata top-right, heavy full-width rule below header, three stat columns with thin vertical borders, large bold values and monospace uppercase labels, footer with filled solid button and monospace string. Typography: heavy geometric sans for headings, monospace for all labels and metadata. Density: medium-tight 14–16px padding. Interaction: no transitions, no hover states — brutalist intentionality. Embellishment: zero — no radius, no shadows, no gradients, hard edges only.',
    v: {
      bg: "#f0f0f0", card: "#ffffff", accent: "#000000", text: "#000000",
      muted: "rgba(0,0,0,0.4)", dimmer: "rgba(0,0,0,0.1)",
      radius: 0, font: "'DM Sans', sans-serif", headSize: 13, headWeight: 900,
      valSize: 18, valWeight: 900, valFont: "'DM Sans', sans-serif",
      labelSize: 6, labelCase: "uppercase", labelSpacing: "0.1em",
      cardPad: 8, gap: 5, cardCount: 3, barCount: 12, barGap: 2,
      showNav: false, showTabs: true, tabStyle: "underline-bold",
      border: "2px solid #000", shadow: "none",
      glass: false, glow: false, brutalist: true, light: true,
      headText: "METRICS", chartLabel: "OUTPUT",
      barAccentStart: 9, titleDecor: "", statSet: "brutalist",
    },
  },
  {
    id: "vapor",
    name: "Vapor",
    tagline: "Frosted layers. Soft glow. Dreamy.",
    icon: "layers",
    density: "spacious",
    typography: "clean",
    interaction: "smooth",
    embellishment: "rich",
    promptText:
      'mood-feel: "vapor" — dual radial ambient gradients from accent colors at 6–8% opacity over the background, frosted glass cards rgba white 0.04 with border rgba white 0.08 border-radius 12px, large values with muted labels, gradient fill progress bar, glowing dot live indicator. Typography: modern geometric sans weight 700 for values, 400 for labels. Density: comfortable 16px padding, 8–10px gaps. Interaction: smooth 200ms ease, subtle glow on hover, gentle scale(1.02). Embellishment: frosted glass throughout, ambient gradient overlay, soft glow on accent elements.',
    v: {
      bg: "#0c0f1a", card: "rgba(255,255,255,0.04)", accent: "#67e8f9", text: "#e0f2fe",
      muted: "rgba(224,242,254,0.35)", dimmer: "rgba(224,242,254,0.12)",
      radius: 16, font: "'DM Sans', sans-serif", headSize: 12, headWeight: 600,
      valSize: 18, valWeight: 700, valFont: "'DM Sans', sans-serif",
      labelSize: 7, labelCase: "normal", labelSpacing: "0.02em",
      cardPad: 12, gap: 10, cardCount: 2, barCount: 12, barGap: 3,
      showNav: false, showTabs: true, tabStyle: "pill",
      border: "1px solid rgba(255,255,255,0.08)", shadow: "0 8px 32px rgba(0,0,0,0.2)",
      glass: true, glow: true, brutalist: false, light: false,
      headText: "Signals", chartLabel: "Frequency",
      barAccentStart: 9, titleDecor: "", statSet: "glass",
    },
  },
  {
    id: "midnight",
    name: "Midnight Luxe",
    tagline: "Dark. Rich. Gold-trimmed.",
    icon: "crown",
    density: "balanced",
    typography: "clean",
    interaction: "smooth",
    embellishment: "moderate",
    promptText:
      'mood-feel: "midnight-luxe" — thin accent gradient crown line top of page, italic serif logo left, glowing accent dot live indicator right, accent gradient horizontal rule, three stat columns with accent-tinted borders, italic serif values, two buttons outlined and filled in accent. Typography: italic serif for logo and values, uppercase letter-spaced sans for labels — restrained and deliberate. Density: 16–18px padding, intentional breathing room. Interaction: smooth 300ms ease, subtle accent glow on hover. Embellishment: hairline accent accents only, no gradients on surfaces, no radius — pure refined darkness.',
    v: {
      bg: "#08090d", card: "#12141c", accent: "#d4a254", text: "#e8e4dc",
      muted: "rgba(232,228,220,0.35)", dimmer: "rgba(232,228,220,0.12)",
      radius: 12, font: "'DM Sans', sans-serif", headSize: 11, headWeight: 700,
      valSize: 18, valWeight: 700, valFont: "'DM Sans', sans-serif",
      labelSize: 6, labelCase: "uppercase", labelSpacing: "0.08em",
      cardPad: 10, gap: 8, cardCount: 3, barCount: 14, barGap: 3,
      showNav: false, showTabs: true, tabStyle: "pill",
      border: "1px solid rgba(212,162,84,0.12)", shadow: "0 2px 12px rgba(0,0,0,0.3)",
      glass: false, glow: false, brutalist: false, light: false,
      headText: "Portfolio", chartLabel: "Returns",
      barAccentStart: 11, titleDecor: "", statSet: "luxe",
    },
  },
  {
    id: "softpaper",
    name: "Soft Paper",
    tagline: "Warm. Rounded. Touchable.",
    icon: "circle",
    density: "spacious",
    typography: "rounded",
    interaction: "smooth",
    embellishment: "moderate",
    promptText:
      'mood-feel: "soft-paper" — muted neutral background, surface cards border-radius 16px with soft box-shadow, large bold values in accent colors, small muted bold labels, full-width rounded pill button. Typography: rounded heavy sans weight 900 for values and logo, 700 for labels — friendly throughout. Density: spacious 18–22px padding, generous internal card padding. Interaction: bouncy 180ms ease-out, scale(1.03) on hover, shadow deepens on press. Embellishment: soft shadows throughout, generous radius 12–18px everywhere, no hard edges.',
    v: {
      bg: "#faf8f5", card: "#ffffff", accent: "#6366f1", text: "#1e1b2e",
      muted: "rgba(30,27,46,0.4)", dimmer: "rgba(30,27,46,0.12)",
      radius: 16, font: "'Nunito', sans-serif", headSize: 12, headWeight: 800,
      valSize: 18, valWeight: 900, valFont: "'Nunito', sans-serif",
      labelSize: 6, labelCase: "normal", labelSpacing: "0.02em",
      cardPad: 12, gap: 10, cardCount: 3, barCount: 10, barGap: 3,
      showNav: false, showTabs: true, tabStyle: "pill",
      border: "1px solid rgba(0,0,0,0.06)", shadow: "0 2px 12px rgba(0,0,0,0.06)",
      glass: false, glow: false, brutalist: false, light: true,
      headText: "Dashboard", chartLabel: "Activity",
      barAccentStart: 7, titleDecor: "", statSet: "default",
    },
  },
  {
    id: "signal",
    name: "Signal",
    tagline: "Clean. Status-driven. Functional.",
    icon: "bell",
    density: "balanced",
    typography: "clean",
    interaction: "smooth",
    embellishment: "minimal",
    promptText:
      'mood-feel: "signal" — bold logo left, small rounded badge right, tinted alert block with dot indicator bold heading and muted description, three surface stat cards with status-toned values, filled primary button and ghost secondary button. Typography: clean humanist sans weight 800 for values, 600 for labels, 500 for body. Density: balanced 14–16px padding, clear hierarchy. Interaction: smooth 150ms ease, border color shifts on hover, buttons depress on click. Embellishment: minimal — 7–8px radius on cards and buttons, 1px borders, status tone is the only decoration.',
    v: {
      bg: "#fafafa", card: "#ffffff", accent: "#3b82f6", text: "#111827",
      muted: "rgba(17,24,39,0.45)", dimmer: "rgba(17,24,39,0.1)",
      radius: 8, font: "'DM Sans', sans-serif", headSize: 12, headWeight: 700,
      valSize: 17, valWeight: 800, valFont: "'DM Sans', sans-serif",
      labelSize: 6, labelCase: "uppercase", labelSpacing: "0.06em",
      cardPad: 10, gap: 8, cardCount: 3, barCount: 12, barGap: 3,
      showNav: false, showTabs: true, tabStyle: "pill",
      border: "1px solid rgba(0,0,0,0.08)", shadow: "0 1px 3px rgba(0,0,0,0.05)",
      glass: false, glow: false, brutalist: false, light: true,
      headText: "Alerts", chartLabel: "Response Time",
      barAccentStart: 9, titleDecor: "", statSet: "default",
    },
  },
  {
    id: "notebook",
    name: "Notebook",
    tagline: "Ruled paper. Serif notes. Handcrafted.",
    icon: "edit",
    density: "balanced",
    typography: "editorial",
    interaction: "subtle",
    embellishment: "moderate",
    promptText:
      'mood-feel: "notebook" — muted paper-toned background with repeating horizontal rules every 24px at low opacity, serif logo left and monospace date right, italic serif section title with thin bottom rule, bulleted list small dot bullets with bold key terms in body text, italic serif footnote with thin top border. Typography: editorial serif italic for titles and logo, monospace for dates and metadata. Density: comfortable 14–16px padding, line-ruled structure provides rhythm. Interaction: no hover states — static document feel. Embellishment: ruled lines only, no shadows, no radius, no fills.',
    v: {
      bg: "#f5f0e6", card: "transparent", accent: "#8b5e3c", text: "#2c2418",
      muted: "rgba(44,36,24,0.4)", dimmer: "rgba(44,36,24,0.1)",
      radius: 0, font: "Georgia, serif", headSize: 14, headWeight: 400,
      valSize: 18, valWeight: 400, valFont: "Georgia, serif",
      labelSize: 6, labelCase: "normal", labelSpacing: "0.02em",
      cardPad: 10, gap: 8, cardCount: 3, barCount: 10, barGap: 4,
      showNav: false, showTabs: false, tabStyle: "none",
      border: "1px solid rgba(44,36,24,0.12)", shadow: "none",
      glass: false, glow: false, brutalist: false, light: true,
      headText: "Field Notes", chartLabel: "Observations",
      barAccentStart: 7, titleDecor: "italic", statSet: "editorial",
    },
  },
  {
    id: "neongrid",
    name: "Neon Grid",
    tagline: "Glowing lines. Grid energy. Electric.",
    icon: "grid",
    density: "compact",
    typography: "technical",
    interaction: "snappy",
    embellishment: "rich",
    promptText:
      'mood-feel: "neon-grid" — subtle line-grid pattern overlay at very low opacity, monospace logo with text-shadow glow, bordered monospace status indicator, three stat cells thin tinted borders with large monospace values in distinct accent tones with text-shadow glow, two horizontal bar indicators with glowing gradient fills. Typography: monospace exclusively, uppercase for all labels, wide letter-spacing, glow on key values. Density: compact 10–14px padding, tight gaps. Interaction: instant 100ms snap, glow intensifies on hover, no scale. Embellishment: text-shadow glow on accent values, grid overlay, glowing gradient bar fills, no border-radius anywhere.',
    v: {
      bg: "#0a0a0f", card: "#111118", accent: "#22d3ee", text: "#e0f2fe",
      muted: "rgba(224,242,254,0.35)", dimmer: "rgba(224,242,254,0.12)",
      radius: 0, font: "'JetBrains Mono', monospace", headSize: 10, headWeight: 600,
      valSize: 15, valWeight: 600, valFont: "'JetBrains Mono', monospace",
      labelSize: 5, labelCase: "uppercase", labelSpacing: "0.12em",
      cardPad: 7, gap: 5, cardCount: 3, barCount: 20, barGap: 2,
      showNav: false, showTabs: false, tabStyle: "none",
      border: "1px solid rgba(34,211,238,0.15)", shadow: "none",
      glass: false, glow: true, brutalist: false, light: false,
      headText: "GRID_CTL", chartLabel: "SIGNAL [Hz]",
      barAccentStart: 16, titleDecor: "", statSet: "terminal",
    },
  },
];

// ── Fine-tune dimensions ──
export const MOOD_DIMS = {
  density: {
    label: "Density",
    desc: "How packed is the UI",
    color: "#3b82f6",
    opts: [
      { id: "spacious", label: "Spacious", desc: "Generous whitespace, large touch targets" },
      { id: "balanced", label: "Balanced", desc: "Standard padding, comfortable reading" },
      { id: "compact", label: "Compact", desc: "Tighter spacing, more content visible" },
      { id: "dense", label: "Dense", desc: "Maximum info density, minimal padding" },
    ],
  },
  typography: {
    label: "Typography",
    desc: "Font personality",
    color: "#a855f7",
    opts: [
      { id: "clean", label: "Clean", desc: "Modern sans-serif, neutral and professional" },
      { id: "technical", label: "Technical", desc: "Monospace-heavy, code-like precision" },
      { id: "editorial", label: "Editorial", desc: "Serif accents, magazine-quality hierarchy" },
      { id: "rounded", label: "Rounded", desc: "Soft, friendly fonts with personality" },
    ],
  },
  interaction: {
    label: "Interaction",
    desc: "Hover and transition energy",
    color: "#f59e0b",
    opts: [
      { id: "subtle", label: "Subtle", desc: "Gentle opacity shifts, understated" },
      { id: "smooth", label: "Smooth", desc: "Fluid easing, polished transitions" },
      { id: "snappy", label: "Snappy", desc: "Quick, responsive, satisfying clicks" },
      { id: "dramatic", label: "Dramatic", desc: "Bold transforms, scale shifts, glows" },
    ],
  },
  embellishment: {
    label: "Embellishment",
    desc: "Visual extras",
    color: "#10b981",
    opts: [
      { id: "none", label: "None", desc: "Pure content, zero decoration" },
      { id: "minimal", label: "Minimal", desc: "Subtle borders and light shadows" },
      { id: "moderate", label: "Moderate", desc: "Gradients, shadows, accent borders" },
      { id: "rich", label: "Rich", desc: "Glows, glass effects, layered textures" },
    ],
  },
};

// ── Quick combos (mood + project type pairings) ──
export const MOOD_COMBOS = [
  { mood: "boardroom", purpose: "keynote", label: "Corporate Deck", desc: "Polished presentation for leadership" },
  { mood: "arcade", purpose: "hangout", label: "Team Rally", desc: "Fun internal engagement tool" },
  { mood: "warroom", purpose: "command-center", label: "Ops Dashboard", desc: "Real-time monitoring center" },
  { mood: "vapor", purpose: "showroom", label: "Product Launch", desc: "Dreamy product showcase" },
  { mood: "frontpage", purpose: "handbook", label: "Knowledge Base", desc: "Editorial documentation site" },
  { mood: "midnight", purpose: "number-cruncher", label: "Executive Intel", desc: "Premium analytics portal" },
];

export const DEFAULT_MOOD_DIMENSIONS = {
  density: "balanced",
  typography: "clean",
  interaction: "smooth",
  embellishment: "minimal",
};

// Prompt descriptions for each dimension value
export const MOOD_PROMPT_MAP = {
  density: {
    spacious: "generous whitespace, large touch targets, breathing room between sections",
    balanced: "standard comfortable spacing, balanced padding",
    compact: "tight spacing, more content visible, reduced padding",
    dense: "maximum information density, minimal padding, every pixel earns its place",
  },
  typography: {
    clean: "modern sans-serif typography (DM Sans, Inter), neutral and professional",
    technical: "monospace-heavy typography (JetBrains Mono, Fira Code), code-like precision and data readability",
    editorial: "serif accents for headings (Georgia, Playfair Display), magazine-quality typographic hierarchy",
    rounded: "soft, friendly fonts (Nunito, Quicksand), rounded letterforms with personality",
  },
  interaction: {
    subtle: "understated hover effects — gentle opacity shifts, minimal motion",
    smooth: "polished transitions — fluid easing (cubic-bezier(0.4, 0, 0.2, 1)), 300-350ms durations",
    snappy: "quick, responsive interactions — 100-150ms ease-out, satisfying click feedback",
    dramatic: "bold hover transforms — scale shifts, glow effects, spring-physics easing",
  },
  embellishment: {
    none: "pure content, zero decoration — flat surfaces and clean geometry only",
    minimal: "subtle borders and light box-shadows only",
    moderate: "gradients, layered shadows, accent-colored borders, subtle depth",
    rich: "glassmorphism, glows, layered textures, backdrop-blur, radial gradients",
  },
};
